config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews,only: [:create]
  end
  resources :review, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  
  validates :name, presence: true
  validates :address, :phone_number, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, presence: true, include {"=> 1..5"}
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [show edit update destroy]
  before_action :set_review, only: [create]

  def index
    @reviews = @restaurant.reviews
end

def new
  @review = @restaurant.reviews.build
end

def create
  @review = @restaurant,reviews,build(review_params)
  if @review.save
    redirect_to product_reviews_path(@restaurant),notice: 'Review was succeffully created'
  else
    render :new, status: :unprocessable_entity
  end
end

def show
end

def edit
end

def update
  if @review,update(review_params)
    rediect_to review_path(@review), notice: 'Review was succeffully created'
  else
    render :edit, status: :unprocessable_entity
  end
end

def destroy@review.destroy
  redirect_to product_review_path(@review,restaurant), notice: 'Review was succeffully created'
end

private

def set_review
  @review = Review.find(params[:id])
end

def set_restaurant
  @restaurant = Restaurant.find(params[:restaurant_id])
end

def review_params
  params.require(:review).permit(:rating, :content, :product_id)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Yelp Mvp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>New Restaurant</h1>
<% @restaurants.each do |restaurant| %>
<li><%= restaurant.name %>, <%= restaurant.address %> <%=restaurant.phone_number%><%= link_to "seedetails", restaurant_path(restaurant) %> </li>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= simple_form_for @restaurant do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1>My Restaurant</h1>

<%= @restaurant.name %>
<%= @restaurant.address %>
<%= @restaurant.phone_number %>